language: swift
osx_image: xcode8.3
xcode_project: Twitt.xcodeproj
xcode_scheme: Twitt
xcode_sdk: iphonesimulator10.0

install:
    - pod repo update
    - pod install

script:
    - xctool -project Twitt.xcodeproj -scheme Twitt build test
